export const dynamic = 'force-dynamic';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { prisma } from '@/lib/prisma';
import { ArrowLeftIcon, EnvelopeIcon, CubeIcon, ShoppingCartIcon, UserGroupIcon, ShieldCheckIcon } from '@heroicons/react/24/outline';
import { StartTenantAccess } from './start-tenant-access';
import { toggleTenantStatus } from '../../actions';

export default async function TenantDetailPage({ params }: { params: Promise<{ tenantId: string }> }) {
  const { tenantId } = await params;
  const tenant = await prisma.tenant.findUnique({ where: { id: tenantId }, select: {
    id: true, name: true, businessName: true, isActive: true, createdAt: true, updatedAt: true,
    users: { orderBy: [{ role: 'asc' }, { createdAt: 'asc' }], select: { id: true, name: true, email: true, role: true, isActive: true } },
    products: { orderBy: { stock: 'asc' }, take: 100, select: { id: true, code: true, name: true, stock: true, lowStockAlert: true, isActive: true, updatedAt: true } },
    orders: { orderBy: { updatedAt: 'desc' }, take: 8, select: { id: true, number: true, customerName: true, status: true, total: true, updatedAt: true, product: { select: { name: true } } } },
    _count: { select: { users: true, products: true, orders: true, leads: true } },
  }});
  if (!tenant) notFound();
  const activeAdmins = tenant.users.filter((u) => u.role === 'ADMIN' && u.isActive);
  const lowStock = tenant.products.filter((p) => p.stock <= p.lowStockAlert);
  const orderGroups = await prisma.order.groupBy({ by: ['status'], where: { tenantId }, _count: { _all: true } });
  const count = (status: string) => orderGroups.find((r) => r.status === status)?._count._all || 0;

  return <div className="space-y-7">
    <Link href="/superadmin/users" className="inline-flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-slate-900"><ArrowLeftIcon className="h-4 w-4" />Back to tenants</Link>
    <header className="grid gap-5 border-b border-slate-300 pb-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="flex flex-wrap items-center gap-3"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#e10600]">Tenant inspection</p><span className={`rounded px-2 py-1 text-[11px] font-bold ${tenant.isActive ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-800'}`}>{tenant.isActive ? 'Active' : 'Inactive'}</span></div><h1 className="mt-2 text-2xl font-bold">{tenant.businessName || tenant.name}</h1>{tenant.businessName && <p className="mt-1 text-sm text-slate-500">Account: {tenant.name}</p>}<p className="mt-3 text-xs text-slate-500">Created {tenant.createdAt.toISOString().slice(0, 10)} · Updated {tenant.updatedAt.toISOString().slice(0, 10)}</p></div><StartTenantAccess tenantId={tenant.id} tenantName={tenant.businessName || tenant.name} admins={activeAdmins.map(({ id, name, email }) => ({ id, name, email }))} tenantActive={tenant.isActive} /></header>

    <div className="grid gap-5 lg:grid-cols-[1.35fr_1fr]"><section className="rounded-md border border-slate-300 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-bold">Operational snapshot</h2></div><div className="grid grid-cols-2 divide-x divide-y divide-slate-200 sm:grid-cols-4">{[[CubeIcon, 'Products', tenant._count.products], [ShoppingCartIcon, 'Orders', tenant._count.orders], [UserGroupIcon, 'Leads', tenant._count.leads], [UserGroupIcon, 'Staff', tenant._count.users]].map(([Icon, label, value]: any) => <div key={label} className="p-4"><Icon className="h-5 w-5 text-slate-400" /><p className="mt-3 text-2xl font-bold tabular-nums">{value}</p><p className="text-xs font-semibold text-slate-500">{label}</p></div>)}</div><div className="grid grid-cols-3 border-t border-slate-200 bg-slate-50"><div className="p-4"><p className="text-xs text-slate-500">Delivered</p><p className="mt-1 font-bold text-emerald-700 tabular-nums">{count('DELIVERED')}</p></div><div className="border-x border-slate-200 p-4"><p className="text-xs text-slate-500">Returned</p><p className="mt-1 font-bold text-amber-700 tabular-nums">{count('RETURNED')}</p></div><div className="p-4"><p className="text-xs text-slate-500">Pending</p><p className="mt-1 font-bold tabular-nums">{count('PENDING')}</p></div></div></section>
      <section className="rounded-md border border-slate-300 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-200 px-5 py-4"><EnvelopeIcon className="h-5 w-5 text-slate-400" /><h2 className="font-bold">Tenant accounts</h2></div><div className="divide-y divide-slate-200">{tenant.users.filter((u) => u.role === 'ADMIN').map((admin) => <div key={admin.id} className="px-5 py-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{admin.name || 'Tenant admin'}</p><span className={`text-[10px] font-bold uppercase ${admin.isActive ? 'text-emerald-700' : 'text-red-700'}`}>{admin.isActive ? 'Active' : 'Inactive'}</span></div><p className="mt-1 break-all text-xs text-slate-500">{admin.email}</p></div>)}{!tenant.users.some((u) => u.role === 'ADMIN') && <p className="px-5 py-8 text-sm text-slate-500">No ADMIN account is configured.</p>}</div></section></div>

    <section className="rounded-md border border-slate-300 bg-white shadow-sm"><div className="flex items-start justify-between border-b border-slate-200 px-5 py-4"><div className="min-w-0"><h2 className="font-bold">Low-stock investigation</h2><p className="mt-1 text-xs text-slate-500">Products at or below their alert threshold</p></div><span className={`ml-3 shrink-0 whitespace-nowrap rounded px-2 py-1 text-xs font-bold ${lowStock.length ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-800'}`}>{lowStock.length} flagged</span></div>{lowStock.length ? <div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50"><tr>{['Code', 'Product', 'On hand', 'Alert at', 'State'].map((h) => <th key={h} className="px-5 py-3 text-left text-[11px] font-bold uppercase text-slate-500">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-200">{lowStock.map((p) => <tr key={p.id}><td className="px-5 py-3 font-mono text-xs">{p.code}</td><td className="px-5 py-3 text-sm font-semibold">{p.name}</td><td className="px-5 py-3 text-sm font-bold tabular-nums">{p.stock}</td><td className="px-5 py-3 text-sm tabular-nums text-slate-500">{p.lowStockAlert}</td><td className="px-5 py-3"><span className={`text-xs font-bold ${p.stock <= 0 ? 'text-red-700' : 'text-amber-700'}`}>{p.stock <= 0 ? 'Out of stock' : 'Low stock'}</span></td></tr>)}</tbody></table></div> : <div className="px-5 py-10 text-center text-sm text-slate-500">No products currently need stock attention.</div>}</section>

    <section className="rounded-md border border-slate-300 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-bold">Recent orders</h2><p className="mt-1 text-xs text-slate-500">Latest tenant order activity</p></div>{tenant.orders.length ? <><div className="divide-y divide-slate-200 sm:hidden">{tenant.orders.map((order) => <article key={order.id} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm font-bold">Order #{order.number}</p><p className="mt-1 break-words text-sm font-semibold text-slate-700">{order.customerName}</p><p className="mt-0.5 break-words text-xs text-slate-500">{order.product.name}</p></div><span className="shrink-0 rounded bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-700">{order.status}</span></div><div className="mt-4 flex items-end justify-between gap-3 border-t border-slate-100 pt-3"><div><p className="text-[10px] font-bold uppercase text-slate-400">Updated</p><p className="mt-0.5 text-xs text-slate-600">{order.updatedAt.toISOString().slice(0, 10)}</p></div><div className="text-right"><p className="text-[10px] font-bold uppercase text-slate-400">Order total</p><p className="mt-0.5 text-sm font-bold tabular-nums">LKR {order.total.toLocaleString('en-LK')}</p></div></div></article>)}</div><div className="hidden overflow-x-auto sm:block"><table className="min-w-full divide-y divide-slate-200"><tbody className="divide-y divide-slate-200">{tenant.orders.map((order) => <tr key={order.id}><td className="px-5 py-3 text-sm font-bold">#{order.number}</td><td className="px-5 py-3"><p className="text-sm font-semibold">{order.customerName}</p><p className="text-xs text-slate-500">{order.product.name}</p></td><td className="px-5 py-3 text-xs font-bold text-slate-600">{order.status}</td><td className="px-5 py-3 text-right text-sm font-semibold tabular-nums">LKR {order.total.toLocaleString('en-LK')}</td><td className="whitespace-nowrap px-5 py-3 text-right text-xs text-slate-500">{order.updatedAt.toISOString().slice(0, 10)}</td></tr>)}</tbody></table></div></> : <div className="px-5 py-10 text-center text-sm text-slate-500">No orders have been recorded.</div>}</section>

    <section className="rounded-md border border-slate-300 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-bold">Account availability</h2><p className="mt-1 text-sm text-slate-500">Deactivation blocks tenant sign-in and read-only workspace access.</p></div><form action={toggleTenantStatus}><input type="hidden" name="tenantId" value={tenant.id} /><input type="hidden" name="isActive" value={String(tenant.isActive)} /><button className={`rounded-md border px-4 py-2 text-sm font-bold ${tenant.isActive ? 'border-red-300 text-red-700 hover:bg-red-50' : 'border-emerald-300 text-emerald-700 hover:bg-emerald-50'}`}>{tenant.isActive ? 'Deactivate tenant' : 'Activate tenant'}</button></form></div></section>
  </div>;
}
