'use client';
import { useState } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { ShieldCheckIcon, XMarkIcon, ClockIcon, LockClosedIcon } from '@heroicons/react/24/outline';
import { Dialog, DialogBackdrop, DialogPanel, DialogTitle } from '@headlessui/react';

export function StartTenantAccess({ tenantId, tenantName, admins, tenantActive }: { tenantId: string; tenantName: string; admins: { id: string; name: string | null; email: string }[]; tenantActive: boolean }) {
  const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const { update } = useSession(); const router = useRouter();
  const available = tenantActive && admins.length > 0;
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setError(''); const form = new FormData(event.currentTarget);
    try { const response = await fetch('/api/superadmin/impersonation/start', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tenantId, targetUserId: form.get('targetUserId'), password: form.get('password'), reason: form.get('reason') }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to start access.'); await update({ impersonationSessionId: data.impersonationSessionId }); router.push('/dashboard'); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to start access.'); setLoading(false); }
  }
  return <><button disabled={!available} onClick={() => setOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-md bg-amber-400 px-4 py-2.5 text-sm font-bold text-slate-950 shadow-sm hover:bg-amber-300 disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-500"><ShieldCheckIcon className="h-5 w-5" />View tenant workspace</button>{!available && <p className="max-w-xs text-xs text-red-700">Requires an active tenant and active ADMIN account.</p>}
    <Dialog open={open} onClose={(nextOpen) => { if (!loading) setOpen(nextOpen); }} className="relative z-[70]">
      <DialogBackdrop transition className="fixed inset-0 bg-slate-950/70 transition-opacity data-[closed]:opacity-0" />
      <div className="fixed inset-0 flex items-center justify-center overflow-y-auto p-4">
        <DialogPanel transition className="relative w-full max-w-lg overflow-hidden rounded-lg bg-white shadow-2xl transition duration-150 data-[closed]:translate-y-2 data-[closed]:opacity-0">
          <div className="border-b border-amber-200 bg-amber-50 p-5 pr-14"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-amber-800">Security checkpoint</p><DialogTitle className="mt-1 text-xl font-bold text-slate-950">View {tenantName}</DialogTitle><p className="mt-2 text-sm leading-6 text-slate-700">This creates a 15-minute, read-only custody session. Every access event is recorded.</p><button aria-label="Close" onClick={() => setOpen(false)} disabled={loading} className="absolute right-4 top-4 rounded-md p-2 text-slate-500 hover:bg-amber-100 focus:outline-none focus:ring-2 focus:ring-amber-700"><XMarkIcon className="h-5 w-5" /></button></div><div className="grid grid-cols-2 border-b border-slate-200 bg-slate-50 text-xs font-semibold text-slate-600"><div className="flex items-center gap-2 border-r border-slate-200 p-3"><LockClosedIcon className="h-4 w-4 text-amber-700" />No changes allowed</div><div className="flex items-center gap-2 p-3"><ClockIcon className="h-4 w-4 text-amber-700" />Expires in 15 minutes</div></div><form onSubmit={submit} className="space-y-4 p-5"><label className="block"><span className="text-sm font-bold">Tenant ADMIN account</span><select autoFocus name="targetUserId" required className="mt-1.5 w-full rounded-md border-slate-300 text-sm focus:border-amber-600 focus:ring-amber-600">{admins.map((a) => <option value={a.id} key={a.id}>{a.name || 'Tenant admin'} — {a.email}</option>)}</select></label><label className="block"><span className="text-sm font-bold">Reason for access</span><textarea name="reason" required minLength={10} maxLength={500} rows={3} placeholder="Example: Review stock reported for a prohibited-item investigation" className="mt-1.5 w-full rounded-md border-slate-300 text-sm focus:border-amber-600 focus:ring-amber-600" /><span className="mt-1 block text-xs text-slate-500">This reason appears in the audit record and custody banner.</span></label><label className="block"><span className="text-sm font-bold">Your current Super Admin password</span><input name="password" type="password" autoComplete="current-password" required className="mt-1.5 w-full rounded-md border-slate-300 text-sm focus:border-amber-600 focus:ring-amber-600" /></label>{error && <p role="alert" className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm font-semibold text-red-700">{error}</p>}<div className="flex flex-col-reverse gap-2 pt-2 sm:flex-row sm:justify-end"><button type="button" onClick={() => setOpen(false)} disabled={loading} className="rounded-md border border-slate-300 px-4 py-2.5 text-sm font-bold hover:bg-slate-50">Cancel</button><button disabled={loading} className="rounded-md bg-slate-950 px-4 py-2.5 text-sm font-bold text-white hover:bg-slate-800 disabled:opacity-60">{loading ? 'Crossing security boundary…' : 'Start read-only access'}</button></div></form>
        </DialogPanel>
      </div>
    </Dialog></>;
}
