'use client';
import { useMemo, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

interface Product { id: string; code: string; name: string; stock?: number }
interface RequestRecord { id: string; tenantId: string; kind: string; status: string; quantity: number; reason: string; reviewNote: string | null; createdAt: Date | string; reviewedAt: Date | string | null; product: Product; requestedBy: { name: string | null }; reviewedBy: { name: string | null } | null; tenant?: { name: string }; stockAdjustment?: { previousStock: number; newStock: number } | null }
const field = 'mt-1 block w-full min-w-0 rounded-md border border-border bg-background px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-primary';
const button = 'rounded-md border border-border px-3 py-2 text-sm font-medium text-foreground hover:bg-muted disabled:opacity-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary';
const dateFormat = new Intl.DateTimeFormat('en-LK', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Colombo' });
const signed = (value: number) => value > 0 ? `+${value}` : String(value);
const titles = { adjustments: 'Stock Adjustment', summary: 'Adjustment Summary', waste: 'Stock Waste', review: 'Review stock requests' };

export function StockRequestClient({ mode, initialRequests, products = [], canCreate = false }: { mode: 'adjustments' | 'summary' | 'waste' | 'review'; initialRequests: RequestRecord[]; products?: Product[]; canCreate?: boolean }) {
    const router = useRouter();
    const [isRefreshing, startRefresh] = useTransition();
    const [status, setStatus] = useState(mode === 'review' ? 'PENDING' : '');
    const [kind, setKind] = useState(mode === 'waste' ? 'WASTE' : '');
    const [productFilter, setProductFilter] = useState('');
    const [tenantFilter, setTenantFilter] = useState('');
    const [from, setFrom] = useState(''); const [to, setTo] = useState('');
    const [productId, setProductId] = useState(''); const [quantity, setQuantity] = useState(''); const [reason, setReason] = useState('');
    const [notes, setNotes] = useState<Record<string, string>>({});
    const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
    const disabled = busy || isRefreshing;
    const visible = useMemo(() => initialRequests.filter(request => (!status || request.status === status) && (!kind || request.kind === kind) && (!tenantFilter || request.tenantId === tenantFilter) && (!productFilter || `${request.product.code} ${request.product.name}`.toLowerCase().includes(productFilter.toLowerCase())) && (!from || new Date(request.createdAt).getTime() >= new Date(`${from}T00:00:00+05:30`).getTime()) && (!to || new Date(request.createdAt).getTime() < new Date(`${to}T00:00:00+05:30`).getTime() + 86400000)), [initialRequests, status, kind, tenantFilter, productFilter, from, to]);
    const tenants = [...new Map(initialRequests.filter(request => request.tenant).map(request => [request.tenantId, request.tenant!.name])).entries()];
    const refresh = () => startRefresh(() => router.refresh());
    const submitRequest = async (event: React.FormEvent) => {
        event.preventDefault(); setError(null); setSuccess(null);
        const delta = mode === 'waste' ? -Number(quantity) : Number(quantity);
        if (!Number.isInteger(delta) || delta === 0 || (mode === 'waste' && delta >= 0)) { setError('Enter a nonzero whole quantity. Waste must be a positive number of units lost.'); return; }
        setBusy(true);
        try {
            const response = await fetch('/api/inventory/requests', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ productId, kind: mode === 'waste' ? 'WASTE' : 'ADJUSTMENT', quantity: delta, reason }) });
            const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to submit request.');
            setQuantity(''); setReason(''); setSuccess('Request submitted for super admin approval. Stock has not changed.'); refresh();
        } catch (err) { setError(err instanceof Error ? err.message : 'Unable to submit request.'); } finally { setBusy(false); }
    };
    const review = async (id: string, decision: 'APPROVED' | 'REJECTED') => {
        setError(null); setSuccess(null);
        if ((notes[id] || '').trim().length < 3) { setError('Enter a review note of at least 3 characters.'); return; }
        setBusy(true);
        try {
            const response = await fetch(`/api/superadmin/stock-requests/${id}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ decision, note: notes[id].trim() }) });
            const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to review request.');
            setSuccess(decision === 'APPROVED' ? 'Request approved and stock movement recorded.' : 'Request rejected. Stock was not changed.'); refresh();
        } catch (err) { setError(err instanceof Error ? err.message : 'Unable to review request.'); refresh(); } finally { setBusy(false); }
    };
    return <div className={`min-w-0 space-y-5 ${mode === 'review' ? '' : 'p-4 sm:p-6 lg:p-8'}`}>
        {mode !== 'review' && <nav aria-label="Stock sections" className="flex flex-wrap gap-2">{[['/inventory', 'Stock List'], ['/inventory/adjustments', 'Stock Adjustment'], ['/inventory/adjustment-summary', 'Adjustment Summary'], ['/inventory/waste', 'Stock Waste']].map(([href, label]) => <Link key={href} href={href} className={`${button} ${label === titles[mode] ? 'bg-muted font-semibold' : ''}`}>{label}</Link>)}</nav>}
        <header><h1 className="text-2xl font-bold text-foreground">{titles[mode]}</h1><p className="mt-1 text-sm text-muted-foreground">{mode === 'review' ? 'Review tenant requests. Approval applies the signed quantity to current stock.' : 'Stock changes only after super admin approval. Pending and rejected requests do not move stock.'}</p></header>
        {error && <p role="alert" className="rounded-md border border-destructive/30 p-3 text-sm text-destructive">{error}</p>}{success && <p role="status" className="rounded-md border border-border bg-muted/30 p-3 text-sm text-foreground">{success}</p>}
        {canCreate && (mode === 'adjustments' || mode === 'waste') && <form onSubmit={submitRequest} className="rounded-xl border border-border bg-card p-4"><h2 className="mb-3 font-semibold text-foreground">{mode === 'waste' ? 'Report stock waste' : 'Request stock adjustment'}</h2><fieldset disabled={disabled} className="grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs text-muted-foreground">Product<select required value={productId} onChange={event => setProductId(event.target.value)} className={field}><option value="">Choose a product</option>{products.map(product => <option key={product.id} value={product.id}>{product.code} · {product.name} ({product.stock} units)</option>)}</select></label><label className="text-xs text-muted-foreground">{mode === 'waste' ? 'Units lost (positive number)' : 'Quantity change (+ add / − remove)'}<input required type="number" step="1" min={mode === 'waste' ? '1' : '-100000'} max="100000" value={quantity} onChange={event => setQuantity(event.target.value)} className={field} /></label><label className="text-xs text-muted-foreground sm:col-span-2">Reason<textarea required minLength={3} maxLength={500} value={reason} onChange={event => setReason(event.target.value)} className={field} /></label><button type="submit" disabled={!products.length} className="w-fit rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50">{disabled ? 'Submitting…' : 'Submit for approval'}</button></fieldset></form>}
        <section aria-label="Request filters" className="rounded-xl border border-border bg-card p-4"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs text-muted-foreground">Status<select value={status} onChange={event => setStatus(event.target.value)} className={field}><option value="">All statuses</option>{['PENDING','APPROVED','REJECTED'].map(value => <option key={value}>{value}</option>)}</select></label>{mode !== 'waste' && <label className="text-xs text-muted-foreground">Kind<select value={kind} onChange={event => setKind(event.target.value)} className={field}><option value="">All kinds</option><option value="ADJUSTMENT">Adjustment</option><option value="WASTE">Waste</option></select></label>}<label className="text-xs text-muted-foreground">Product name or code<input value={productFilter} onChange={event => setProductFilter(event.target.value)} className={field} /></label>{mode === 'review' && <label className="text-xs text-muted-foreground">Tenant<select value={tenantFilter} onChange={event => setTenantFilter(event.target.value)} className={field}><option value="">All tenants</option>{tenants.map(([id,name]) => <option key={id} value={id}>{name}</option>)}</select></label>}<label className="text-xs text-muted-foreground">Requested from<input type="date" value={from} onChange={event => setFrom(event.target.value)} className={field} /></label><label className="text-xs text-muted-foreground">Requested to<input type="date" value={to} onChange={event => setTo(event.target.value)} className={field} /></label></div><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted-foreground">Latest 500 requests · {visible.length} matching · Sri Lanka dates</p><button onClick={() => { setStatus(''); setKind(mode === 'waste' ? 'WASTE' : ''); setProductFilter(''); setTenantFilter(''); setFrom(''); setTo(''); }} className={button}>Clear filters</button></div></section>
        <div className="flex flex-wrap gap-x-6 gap-y-2 rounded-md border border-border bg-card p-4 text-sm text-foreground">{['PENDING','APPROVED','REJECTED'].map(value => <span key={value}>{value.toLowerCase()}: <strong>{visible.filter(request => request.status === value).length}</strong></span>)}<span>Approved net movement: <strong>{signed(visible.filter(request => request.status === 'APPROVED').reduce((sum,request) => sum + request.quantity,0))} units</strong></span></div>
        <section aria-label="Stock change requests" className="space-y-3">{visible.length === 0 ? <div className="rounded-xl border border-border bg-card p-10 text-center text-sm text-muted-foreground">No requests match these filters.</div> : visible.map(request => <article key={request.id} className="rounded-xl border border-border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-foreground">{request.product.code} · {request.product.name}</h2><p className="mt-1 text-xs text-muted-foreground">{request.tenant?.name ? `${request.tenant.name} · ` : ''}{request.kind} · {request.requestedBy.name || 'Unnamed staff'} · {dateFormat.format(new Date(request.createdAt))}</p></div><span className="rounded-md bg-muted px-2 py-1 text-xs font-semibold text-foreground">{request.status}</span></div><p className="mt-3 break-words text-sm text-foreground">{request.reason}</p><p className="mt-2 text-sm text-foreground">Requested change: <strong>{signed(request.quantity)} units</strong>{request.stockAdjustment && <span className="ml-3">Applied: {request.stockAdjustment.previousStock} → {request.stockAdjustment.newStock}</span>}</p>{request.reviewNote && <p className="mt-2 break-words text-sm text-muted-foreground">Review: {request.reviewNote} · {request.reviewedBy?.name || 'Super admin'}{request.reviewedAt ? ` · ${dateFormat.format(new Date(request.reviewedAt))}` : ''}</p>}{mode === 'review' && request.status === 'PENDING' && <div className="mt-4 border-t border-border pt-3"><p className="text-sm text-muted-foreground">Current stock: {request.product.stock} · Proposed balance: {(request.product.stock ?? 0) + request.quantity}. Rechecked when approved.</p><label className="mt-3 block text-xs text-muted-foreground">Review note (required)<textarea minLength={3} maxLength={500} disabled={disabled} value={notes[request.id] || ''} onChange={event => setNotes(current => ({ ...current, [request.id]: event.target.value }))} className={field} /></label><div className="mt-3 flex gap-2"><button disabled={disabled || (notes[request.id] || '').trim().length < 3} onClick={() => review(request.id, 'APPROVED')} className="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50">Approve &amp; apply stock</button><button disabled={disabled || (notes[request.id] || '').trim().length < 3} onClick={() => review(request.id, 'REJECTED')} className={button}>Reject request</button></div></div>}</article>)}</section>
    </div>;
}
