'use client';
import { useEffect, useState } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { ClockIcon, ArrowLeftOnRectangleIcon, ShieldExclamationIcon } from '@heroicons/react/24/outline';

type Access = { sessionId: string; tenantId: string; tenantName: string; reason: string; mode: 'READ_ONLY'; startedAt: string; expiresAt: string };
export function ImpersonationBanner({ access, actorName }: { access: Access; actorName: string }) {
  const { update } = useSession(); const router = useRouter(); const [remaining, setRemaining] = useState(''); const [ending, setEnding] = useState(false);
  useEffect(() => { const tick = () => { const seconds = Math.max(0, Math.ceil((Date.parse(access.expiresAt) - Date.now()) / 1000)); setRemaining(`${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`); }; tick(); const timer = setInterval(tick, 1000); return () => clearInterval(timer); }, [access.expiresAt]);
  async function exit() { setEnding(true); try { await fetch('/api/superadmin/impersonation/end', { method: 'POST' }); await update({ impersonationSessionId: null }); router.push(`/superadmin/tenants/${access.tenantId}`); router.refresh(); } finally { setEnding(false); } }
  return <section aria-label="Read-only Super Admin access" className="relative z-40 border-b border-amber-500 bg-amber-300 px-3 py-3 text-slate-950 shadow-[0_2px_0_rgba(15,23,42,0.18)] sm:px-5"><div className="mx-auto flex max-w-[1600px] flex-col gap-3 lg:flex-row lg:items-center"><div className="flex min-w-0 flex-1 items-start gap-3"><span className="shrink-0 rounded-md bg-slate-950 p-2 text-amber-300"><ShieldExclamationIcon className="h-5 w-5" /></span><div className="min-w-0"><p className="break-words font-black leading-5">Read-only · Viewing {access.tenantName} as Super Admin</p><dl className="mt-1 space-y-0.5 text-xs leading-5 text-slate-700"><div className="flex flex-wrap gap-x-1"><dt className="font-bold">Actor:</dt><dd className="break-words font-semibold">{actorName}</dd></div><div className="flex items-start gap-x-1"><dt className="shrink-0 font-bold">Reason:</dt><dd className="min-w-0 break-words font-semibold">{access.reason}</dd></div></dl></div></div><div className="flex items-center justify-between gap-3 lg:justify-end"><div className="flex shrink-0 items-center gap-2 rounded-md border border-amber-600/50 bg-amber-100 px-3 py-2 font-mono text-sm font-black tabular-nums"><ClockIcon className="h-4 w-4" /><span aria-label={`${remaining} remaining`}>{remaining}</span></div><button onClick={exit} disabled={ending} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-slate-950 px-4 py-2 text-sm font-black text-white hover:bg-slate-800 focus:outline-none focus:ring-2 focus:ring-white disabled:opacity-60"><ArrowLeftOnRectangleIcon className="h-5 w-5" />{ending ? 'Exiting…' : 'Exit tenant view'}</button></div></div></section>;
}
