export const dynamic = 'force-dynamic';
import Link from 'next/link';
import { prisma } from '@/lib/prisma';
import { MagnifyingGlassIcon, ShieldCheckIcon } from '@heroicons/react/24/outline';

const labels: Record<string, { label: string; tone: string }> = {
  IMPERSONATION_STARTED: { label: 'Access started', tone: 'bg-amber-100 text-amber-800' },
  TENANT_WORKSPACE_VIEWED: { label: 'Workspace viewed', tone: 'bg-blue-50 text-blue-800' },
  IMPERSONATION_ENDED: { label: 'Access ended', tone: 'bg-slate-100 text-slate-700' },
  TENANT_STATUS_CHANGED: { label: 'Tenant status changed', tone: 'bg-red-50 text-red-700' },
  SUPER_ADMIN_CREATED: { label: 'Super Admin created', tone: 'bg-violet-50 text-violet-700' },
  SUPER_ADMIN_PASSWORD_CHANGED: { label: 'Security credential changed', tone: 'bg-violet-50 text-violet-700' },
};

export default async function AuditPage({ searchParams }: { searchParams: Promise<{ q?: string; action?: string; tenant?: string }> }) {
  const params = await searchParams; const q = params.q?.trim() || ''; const action = params.action || ''; const tenantId = params.tenant || '';
  const [events, tenants] = await Promise.all([
    prisma.auditEvent.findMany({ where: { ...(action ? { action } : {}), ...(tenantId ? { tenantId } : {}), ...(q ? { OR: [{ actor: { email: { contains: q, mode: 'insensitive' } } }, { actor: { name: { contains: q, mode: 'insensitive' } } }, { tenant: { name: { contains: q, mode: 'insensitive' } } }, { entityId: { contains: q, mode: 'insensitive' } }] } : {}) }, orderBy: { createdAt: 'desc' }, take: 250, select: { id: true, action: true, entityType: true, entityId: true, metadata: true, ipAddress: true, userAgent: true, createdAt: true, impersonationSessionId: true, actor: { select: { name: true, email: true } }, tenant: { select: { id: true, name: true } } } }),
    prisma.tenant.findMany({ orderBy: { name: 'asc' }, select: { id: true, name: true } }),
  ]);
  return <div className="space-y-6"><div className="border-b border-slate-300 pb-6"><div className="flex items-center gap-2 text-[#e10600]"><ShieldCheckIcon className="h-5 w-5" /><p className="text-[11px] font-bold uppercase tracking-[0.18em]">Security custody record</p></div><h1 className="mt-2 text-2xl font-bold">Audit log</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">An append-only history of tenant access and sensitive owner actions. Showing the latest 250 events.</p></div>
    <form className="grid gap-3 rounded-md border border-slate-300 bg-white p-4 shadow-sm lg:grid-cols-[1fr_220px_220px_auto]"><label className="relative"><span className="sr-only">Search audit records</span><MagnifyingGlassIcon className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input name="q" defaultValue={q} placeholder="Actor, tenant, or entity ID" className="w-full rounded-md border-slate-300 py-2 pl-9 text-sm focus:border-red-500 focus:ring-red-500" /></label><select name="action" defaultValue={action} aria-label="Event type" className="rounded-md border-slate-300 text-sm focus:border-red-500 focus:ring-red-500"><option value="">All event types</option>{Object.entries(labels).map(([value, item]) => <option key={value} value={value}>{item.label}</option>)}</select><select name="tenant" defaultValue={tenantId} aria-label="Tenant" className="rounded-md border-slate-300 text-sm focus:border-red-500 focus:ring-red-500"><option value="">All tenants</option>{tenants.map((t) => <option value={t.id} key={t.id}>{t.name}</option>)}</select><button className="rounded-md bg-slate-900 px-5 py-2 text-sm font-bold text-white hover:bg-slate-700">Apply</button></form>
    <div className="overflow-hidden rounded-md border border-slate-300 bg-white shadow-sm">{events.length ? <div className="divide-y divide-slate-200">{events.map((event) => { const detail = labels[event.action] || { label: event.action.replaceAll('_', ' ').toLowerCase(), tone: 'bg-slate-100 text-slate-700' }; const metadata = event.metadata && typeof event.metadata === 'object' ? event.metadata as Record<string, unknown> : {}; return <article key={event.id} className="grid gap-3 px-5 py-4 hover:bg-slate-50 lg:grid-cols-[180px_190px_1fr_190px]"><div><span className={`inline-flex rounded px-2 py-1 text-[11px] font-bold ${detail.tone}`}>{detail.label}</span><p className="mt-2 text-[11px] text-slate-500">{event.createdAt.toISOString().replace('T', ' ').slice(0, 19)} UTC</p></div><div><p className="text-sm font-bold">{event.actor.name || 'Super Admin'}</p><p className="mt-1 break-all text-xs text-slate-500">{event.actor.email}</p></div><div><p className="text-sm font-semibold">{event.tenant ? <Link href={`/superadmin/tenants/${event.tenant.id}`} className="hover:text-[#c50500] hover:underline">{event.tenant.name}</Link> : 'Platform security'}</p>{typeof metadata.reason === 'string' && <p className="mt-1 text-xs leading-5 text-slate-600">Reason: {metadata.reason}</p>}<p className="mt-1 font-mono text-[10px] text-slate-400">{event.impersonationSessionId ? `Session ${event.impersonationSessionId}` : event.entityId ? `${event.entityType || 'Entity'} ${event.entityId}` : ''}</p></div><div className="text-xs text-slate-500"><p>{event.ipAddress || 'IP not supplied'}</p><p className="mt-1 truncate" title={event.userAgent || ''}>{event.userAgent || 'User agent not supplied'}</p></div></article>; })}</div> : <div className="px-5 py-16 text-center"><ShieldCheckIcon className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 font-bold">No audit events found</p><p className="mt-1 text-sm text-slate-500">Access and security events will appear here.</p></div>}</div>
  </div>;
}
